### ISSUE TITLE
Single Sign On is misconfigured

### ISSUE THREAD

**Issue by jangrewe** [blackducksoftware/hub#26]
Our upgrading woes continue...

In our previous deployment (v4.3.1) we had the `SAML_IDP_Metadata.xml` that gets uploaded to `/opt/blackduck/hub/hub-webapp/security/SAML_IDP_Metadata.xml` mounted from a ConfigMap into the `nginx-webapp-logstash` pod, into that very same location it gets uploaded to - and it was working fine.

While (still) upgrading to v4.7.0, i discovered after way too many retries that the XML now gets uploaded to the `hub-authentication` pod, to `/opt/blackduck/hub/hub-authentication/security/SAML_IDP_Metadata.xml`. No big deal, so i changed the ConfigMap mounting to that location in that pod, after verifying that this is indeed the correct location if you upload it via the web interface.

But it still doesn't work!

```
[webapp-logstash-846d6f5fb9-r8ft5 webapp] 2018-06-27 15:54:18,912 [https-openssl-apr-8443-exec-1] ERROR com.blackducksoftware.usermgmt.sso.impl.BdsSAMLEntryPoint - Single Sign On is misconfigured. Error = javax.servlet.ServletException: org.opensaml.saml2.metadata.provider.MetadataProviderException: No IDP was configured, please update included metadata with at least one IDP 
[webapp-logstash-846d6f5fb9-r8ft5 webapp] at org.springframework.security.saml.SAMLEntryPoint.commence(SAMLEntryPoint.java:161) 
[webapp-logstash-846d6f5fb9-r8ft5 webapp] at com.blackducksoftware.usermgmt.sso.impl.BdsSAMLEntryPoint.commence(BdsSAMLEntryPoint.java:70) 
[webapp-logstash-846d6f5fb9-r8ft5 webapp] at org.springframework.security.web.access.ExceptionTranslationFilter.sendStartAuthentication(ExceptionTranslationFilter.java:204) 
[webapp-logstash-846d6f5fb9-r8ft5 webapp] at org.springframework.security.web.access.ExceptionTranslationFilter.handleSpringSecurityException(ExceptionTranslationFilter.java:178) 
[webapp-logstash-846d6f5fb9-r8ft5 webapp] at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:134) 
[webapp-logstash-846d6f5fb9-r8ft5 webapp] at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331) 
[webapp-logstash-846d6f5fb9-r8ft5 webapp] at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:137) 
[webapp-logstash-846d6f5fb9-r8ft5 webapp] at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331) 
[webapp-logstash-846d6f5fb9-r8ft5 webapp] at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:111) 
[webapp-logstash-846d6f5fb9-r8ft5 webapp] at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331) 
[webapp-logstash-846d6f5fb9-r8ft5 webapp] at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63) 
[webapp-logstash-846d6f5fb9-r8ft5 webapp] at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331) 
[webapp-logstash-846d6f5fb9-r8ft5 webapp] at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:208) 
[webapp-logstash-846d6f5fb9-r8ft5 webapp] at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:185) 
[webapp-logstash-846d6f5fb9-r8ft5 webapp] at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331) 
[webapp-logstash-846d6f5fb9-r8ft5 webapp] at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:200) 
[webapp-logstash-846d6f5fb9-r8ft5 webapp] at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331) 
[webapp-logstash-846d6f5fb9-r8ft5 webapp] at org.springframework.security.oauth2.provider.authentication.OAuth2AuthenticationProcessingFilter.doFilter(OAuth2AuthenticationProcessingFilter.java:176) 
[webapp-logstash-846d6f5fb9-r8ft5 webapp] at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331) 
[webapp-logstash-846d6f5fb9-r8ft5 webapp] at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:121) 
[webapp-logstash-846d6f5fb9-r8ft5 webapp] at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331) 
[webapp-logstash-846d6f5fb9-r8ft5 webapp] at org.springframework.security.saml.SAMLLogoutFilter.processLogout(SAMLLogoutFilter.java:164) 
[webapp-logstash-846d6f5fb9-r8ft5 webapp] at org.springframework.security.saml.SAMLLogoutFilter.doFilter(SAMLLogoutFilter.java:106) 
[webapp-logstash-846d6f5fb9-r8ft5 webapp] at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331) 
[webapp-logstash-846d6f5fb9-r8ft5 webapp] at com.blackducksoftware.core.app.impl.CsrfTokenBinderFilter.doFilterInternal(CsrfTokenBinderFilter.java:55) 
[webapp-logstash-846d6f5fb9-r8ft5 webapp] at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) 
[webapp-logstash-846d6f5fb9-r8ft5 webapp] at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331) 
[webapp-logstash-846d6f5fb9-r8ft5 webapp] at org.springframework.security.web.csrf.CsrfFilter.doFilterInternal(CsrfFilter.java:100) 
[webapp-logstash-846d6f5fb9-r8ft5 webapp] at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) 
[webapp-logstash-846d6f5fb9-r8ft5 webapp] at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331) 
[webapp-logstash-846d6f5fb9-r8ft5 webapp] at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:66) 
[webapp-logstash-846d6f5fb9-r8ft5 webapp] at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) 
[webapp-logstash-846d6f5fb9-r8ft5 webapp] at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331) 
[webapp-logstash-846d6f5fb9-r8ft5 webapp] at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:101) 
[webapp-logstash-846d6f5fb9-r8ft5 webapp] at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331) 
[webapp-logstash-846d6f5fb9-r8ft5 webapp] at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105) 
[webapp-logstash-846d6f5fb9-r8ft5 webapp] at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331) 
[webapp-logstash-846d6f5fb9-r8ft5 webapp] at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:56) 
[webapp-logstash-846d6f5fb9-r8ft5 webapp] at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) 
[webapp-logstash-846d6f5fb9-r8ft5 webapp] at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331) 
[webapp-logstash-846d6f5fb9-r8ft5 webapp] at org.springframework.security.saml.metadata.MetadataGeneratorFilter.doFilter(MetadataGeneratorFilter.java:87) 
[webapp-logstash-846d6f5fb9-r8ft5 webapp] at com.blackducksoftware.usermgmt.sso.impl.BdsSAMLMetadataGeneratorFilter.doFilter(BdsSAMLMetadataGeneratorFilter.java:50) 
[webapp-logstash-846d6f5fb9-r8ft5 webapp] at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331) 
[webapp-logstash-846d6f5fb9-r8ft5 webapp] at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:214) 
[webapp-logstash-846d6f5fb9-r8ft5 webapp] at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:177) 
[webapp-logstash-846d6f5fb9-r8ft5 webapp] at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346) 
[webapp-logstash-846d6f5fb9-r8ft5 webapp] at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:262) 
[webapp-logstash-846d6f5fb9-r8ft5 webapp] at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) 
[webapp-logstash-846d6f5fb9-r8ft5 webapp] at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) 
[webapp-logstash-846d6f5fb9-r8ft5 webapp] at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198) 
[webapp-logstash-846d6f5fb9-r8ft5 webapp] at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) 
[webapp-logstash-846d6f5fb9-r8ft5 webapp] at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:496) 
[webapp-logstash-846d6f5fb9-r8ft5 webapp] at org.apache.catalina.valves.rewrite.RewriteValve.invoke(RewriteValve.java:542) 
[webapp-logstash-846d6f5fb9-r8ft5 webapp] at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140) 
[webapp-logstash-846d6f5fb9-r8ft5 webapp] at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81) 
[webapp-logstash-846d6f5fb9-r8ft5 webapp] at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:677) 
[webapp-logstash-846d6f5fb9-r8ft5 webapp] at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650) 
[webapp-logstash-846d6f5fb9-r8ft5 webapp] at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87) 
[webapp-logstash-846d6f5fb9-r8ft5 webapp] at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342) 
[webapp-logstash-846d6f5fb9-r8ft5 webapp] at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:803) 
[webapp-logstash-846d6f5fb9-r8ft5 webapp] at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) 
[webapp-logstash-846d6f5fb9-r8ft5 webapp] at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:790) 
[webapp-logstash-846d6f5fb9-r8ft5 webapp] at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.doRun(AprEndpoint.java:2381) 
[webapp-logstash-846d6f5fb9-r8ft5 webapp] at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) 
[webapp-logstash-846d6f5fb9-r8ft5 webapp] at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) 
[webapp-logstash-846d6f5fb9-r8ft5 webapp] at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) 
[webapp-logstash-846d6f5fb9-r8ft5 webapp] at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) 
[webapp-logstash-846d6f5fb9-r8ft5 webapp] at java.lang.Thread.run(Thread.java:748) 
[webapp-logstash-846d6f5fb9-r8ft5 webapp] Caused by: org.opensaml.saml2.metadata.provider.MetadataProviderException: No IDP was configured, please update included metadata with at least one IDP 
[webapp-logstash-846d6f5fb9-r8ft5 webapp] at org.springframework.security.saml.metadata.MetadataManager.getDefaultIDP(MetadataManager.java:795) 
[webapp-logstash-846d6f5fb9-r8ft5 webapp] at org.springframework.security.saml.context.SAMLContextProviderImpl.populatePeerEntityId(SAMLContextProviderImpl.java:157) 
[webapp-logstash-846d6f5fb9-r8ft5 webapp] at org.springframework.security.saml.context.SAMLContextProviderImpl.getLocalAndPeerEntity(SAMLContextProviderImpl.java:127) 
[webapp-logstash-846d6f5fb9-r8ft5 webapp] at org.springframework.security.saml.SAMLEntryPoint.commence(SAMLEntryPoint.java:146) 
[webapp-logstash-846d6f5fb9-r8ft5 webapp] ... 67 more 
[webapp-logstash-846d6f5fb9-r8ft5 webapp]  
[webapp-logstash-846d6f5fb9-r8ft5 webapp] Authenticating using form login...
```
... and then it presents me with the "local" login form.

Clicking the `Download Current XML File` link throws a 404, so it doesn't even see it.

That's very confusing, as the log also mentions this:
```
[hub-authentication-57bdb88564-cmkkd] 2018-06-27 16:03:17.860  INFO 1 --- [ost-startStop-1] .s.m.p.AbstractReloadingMetadataProvider : New metadata succesfully loaded for '/opt/blackduck/hub/hub-authentication/security/SAML_IDP_Metadata.xml' 
[hub-authentication-57bdb88564-cmkkd] 2018-06-27 16:03:17.861  INFO 1 --- [ost-startStop-1] .s.m.p.AbstractReloadingMetadataProvider : Next refresh cycle for metadata provider '/opt/blackduck/hub/hub-authentication/security/SAML_IDP_Metadata.xml' will occur on '2018-06-27T19:03:17.822Z' ('2018-06-27T19:03:17.822Z' local time)
```

**Comment by jangrewe** [comment]
Alright, we were able to fix this with help from the support. There's supposedly a bug that that doesn't upload the XML to the *2* locations where it is required, which is why i didn't discover this earlier:

The XML needs to be mounted in both the `webapp-logstash` (at `/opt/blackduck/hub/hub-webapp/security/SAML_IDP_Metadata.xml`) **AND** the `hub-authentication` (at `/opt/blackduck/hub/hub-authentication/security/SAML_IDP_Metadata.xml`) container, then it works fine.
